os: osx

osx_image: xcode7.3

language: cpp

compiler:
    - clang
    - gcc

install:
    - brew install wget cmake
    - ./scripts/build-deps-unix.sh

script: ./scripts/build.sh && make -C build/tests
