os: osx

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode9

language: cpp

compiler:
    - clang
    - gcc

install:
    - brew install wget cmake
    - ./scripts/build-deps-mac.sh

script: ./scripts/build.sh && make -C build/tests && make -C build/tests test
