version: 0.1.{build}
clone_folder: C:\erpiko
os: Visual Studio 2015
platform:
    - Win32
    - x64
configuration:
    - Debug
    - Release
init:
- 'echo System architecture: %PLATFORM%'
- ps: iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))
- cmd: cmake --version
- cmd: msbuild /version

install:
- cmd: >-    
    choco install wget
    
    choco install unzip
    
    mkdir deps
    
    cd deps
    
    wget -O tip.zip https://github.com/mdamt/libressl-portable/archive/tip.zip
    
    unzip tip.zip
    
    cd libressl-portable-tip
    
    C:\cygwin\bin\bash -lc "cd /cygdrive/c/erpiko/deps/libressl-portable-tip/ && bash autogen.sh"'
    
    C:\cygwin\bin\bash -lc "cd /cygdrive/c/erpiko/deps/libressl-portable-tip/ && patch -p0 < ../../patch/cmp.patch"'
    
    C:\cygwin\bin\bash -lc "cd /cygdrive/c/erpiko/deps/libressl-portable-tip/ && patch -p1 < ../../patch/CMakefiles.patch"'
    
    cd ..
    
    xcopy libressl-portable-tip libressl /e/i
    
    cd libressl

    mkdir build
    
    cd build

    if "%platform%"=="Win32" set CALL_VS=call "%VS140COMNTOOLS%\..\..\vc\vcvarsall.bat" x86
    
    if "%platform%"=="x64" set CALL_VS=call "%VS140COMNTOOLS%\..\..\vc\vcvarsall.bat" amd64
    
    if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015

    if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64

    cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%CONFIGURATION% ..
    
    msbuild LibreSSL.sln /p:Configuration=%CONFIGURATION%

    copy ssl\%CONFIGURATION%\ssl.lib ..\ssl\

    copy tls\%CONFIGURATION%\tls.lib ..\tls\

    copy crypto\%CONFIGURATION%\crypto.lib ..\crypto\

    mkdir ..\ssl\Debug

    mkdir ..\tls\Debug

    mkdir ..\crypto\Debug

    copy ssl\%CONFIGURATION%\ssl.lib ..\ssl\Debug\

    copy tls\%CONFIGURATION%\tls.lib ..\tls\Debug\

    copy crypto\%CONFIGURATION%\crypto.lib ..\crypto\Debug\
            
    cd ..\..
    
    mkdir catch
    
    cd catch
    
    wget -O catch.hpp https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp
    
    cd C:\erpiko
build_script:
- cmd: >-    
    mkdir build
    
    cd build

    if "%platform%"=="Win32" set CALL_VS=call "%VS140COMNTOOLS%\..\..\vc\vcvarsall.bat" x86
    
    if "%platform%"=="x64" set CALL_VS=call "%VS140COMNTOOLS%\..\..\vc\vcvarsall.bat" amd64   
    
    if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015

    if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64

    cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%CONFIGURATION% ..
    
    msbuild erpiko.sln /p:Configuration=%CONFIGURATION%
    
    cd C:\erpiko
test_script:
- cmd: >-
    cd build
    
    cd tests
    
    %CONFIGURATION%\testbase.exe
    
    %CONFIGURATION%\testcertificate.exe
    
    %CONFIGURATION%\testcipher.exe
    
    %CONFIGURATION%\testcmp.exe
    
    %CONFIGURATION%\testdata.exe
    
    %CONFIGURATION%\testdigest.exe
    
    %CONFIGURATION%\testkey.exe
    
    %CONFIGURATION%\testrng.exe
    
    %CONFIGURATION%\testsmime.exe
    
    %CONFIGURATION%\testtsa.exe

    cd C:\erpiko
    
    mkdir erpiko

    cd erpiko

    mkdir lib

    copy ..\deps\libressl\ssl\ssl.lib lib\

    copy ..\deps\libressl\tls\tls.lib lib\

    copy ..\deps\libressl\crypto\crypto.lib lib\

    copy ..\build\src\%CONFIGURATION%\erpiko.lib lib\

    xcopy ..\include include /e/i

artifacts:
- path: erpiko\%CONFIGURATION%\erpiko-%CONFIGURATION%.zip
  name: erpiko
